import 'package:animal_hope/model/species.dart';

import './animal.dart';

// ignore: camel_case_types
class DUMMY_DATA {
  List<Animal> loadAnimals() {
    var animalList = [
      Animal('1',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_1_small.jpg',
          bigImage: 'assets/images/cats/cat_1_big.jpg'),
      Animal('2',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_2_small.jpg',
          bigImage: 'assets/images/cats/cat_2_big.jpg'),
      Animal('3',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_3_small.jpg',
          bigImage: 'assets/images/cats/cat_3_big.jpg'),
      Animal('4',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_4_small.jpg',
          bigImage: 'assets/images/cats/cat_4_big.jpg'),
      Animal('5',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_5_small.jpg',
          bigImage: 'assets/images/cats/cat_5_big.jpg'),
      Animal('6',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_6_small.jpg',
          bigImage: 'assets/images/cats/cat_6_big.jpg'),
      Animal('7',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_7_small.jpg',
          bigImage: 'assets/images/cats/cat_7_big.jpg'),
      Animal('8',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_8_small.jpg',
          bigImage: 'assets/images/cats/cat_8_big.jpg'),
      Animal('9',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_9_small.jpg',
          bigImage: 'assets/images/cats/cat_9_big.jpg'),
      Animal('10',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_10_small.jpg',
          bigImage: 'assets/images/cats/cat_10_big.jpg'),
      Animal('11',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_11_small.jpg',
          bigImage: 'assets/images/cats/cat_11_big.jpg'),
      Animal('12',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_12_small.jpg',
          bigImage: 'assets/images/cats/cat_12_big.jpg'),
      Animal('13',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_13_small.jpg',
          bigImage: 'assets/images/cats/cat_13_big.jpg'),
      Animal('14',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_14_small.jpg',
          bigImage: 'assets/images/cats/cat_14_big.jpg'),
      Animal('15',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_15_small.jpg',
          bigImage: 'assets/images/cats/cat_15_big.jpg'),
      Animal('16',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_16_small.jpg',
          bigImage: 'assets/images/cats/cat_16_big.jpg'),
      Animal('17',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_17_small.jpg',
          bigImage: 'assets/images/cats/cat_17_big.jpg'),
      Animal('18',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_18_small.jpg',
          bigImage: 'assets/images/cats/cat_18_big.jpg'),
      Animal('19',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_19_small.jpg',
          bigImage: 'assets/images/cats/cat_19_big.jpg'),
      Animal('20',
          species: Species.Cat,
          smallImage: 'assets/images/cats/cat_20_small.jpg',
          bigImage: 'assets/images/cats/cat_20_big.jpg'),
      Animal('21',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_1_small.jpg',
          bigImage: 'assets/images/dogs/dog_1_big.jpg'),
      Animal('22',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_2_small.jpg',
          bigImage: 'assets/images/dogs/dog_2_big.jpg'),
      Animal('23',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_3_small.jpg',
          bigImage: 'assets/images/dogs/dog_3_big.jpg'),
      Animal('24',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_4_small.jpg',
          bigImage: 'assets/images/dogs/dog_4_big.jpg'),
      Animal('25',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_5_small.jpg',
          bigImage: 'assets/images/dogs/dog_5_big.jpg'),
      Animal('26',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_6_small.jpg',
          bigImage: 'assets/images/dogs/dog_6_big.jpg'),
      Animal('27',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_7_small.jpg',
          bigImage: 'assets/images/dogs/dog_7_big.jpg'),
      Animal('28',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_8_small.jpg',
          bigImage: 'assets/images/dogs/dog_8_big.jpg'),
      Animal('29',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_9_small.jpg',
          bigImage: 'assets/images/dogs/dog_9_big.jpg'),
      Animal('30',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_10_small.jpg',
          bigImage: 'assets/images/dogs/dog_10_big.jpg'),
      Animal('31',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_11_small.jpg',
          bigImage: 'assets/images/dogs/dog_11_big.jpg'),
      Animal('32',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_12_small.jpg',
          bigImage: 'assets/images/dogs/dog_12_big.jpg'),
      Animal('33',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_13_small.jpg',
          bigImage: 'assets/images/dogs/dog_13_big.jpg'),
      Animal('34',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_14_small.jpg',
          bigImage: 'assets/images/dogs/dog_14_big.jpg'),
      Animal('35',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_15_small.jpg',
          bigImage: 'assets/images/dogs/dog_15_big.jpg'),
      Animal('36',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_16_small.jpg',
          bigImage: 'assets/images/dogs/dog_16_big.jpg'),
      Animal('37',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_17_small.jpg',
          bigImage: 'assets/images/dogs/dog_17_big.jpg'),
      Animal('38',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_18_small.jpg',
          bigImage: 'assets/images/dogs/dog_18_big.jpg'),
      Animal('39',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_19_small.jpg',
          bigImage: 'assets/images/dogs/dog_19_big.jpg'),
      Animal('40',
          species: Species.Dog,
          smallImage: 'assets/images/dogs/dog_20_small.jpg',
          bigImage: 'assets/images/dogs/dog_20_big.jpg'),
    ];

    return animalList;
  }

  List<Animal> getAnimalsBySpecies(Species species) {
    return loadAnimals().where((animal) => animal.species == species).toList();
  }
}
